name: Update git submodule and raise PR

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Downstream Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check token permissions
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Submodule
        run: |
       
          git submodule update --remote --merge
          git add demo2
          
          if [[ -n $(git diff --cached) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            OLD=$(git ls-tree HEAD demo2 | awk '{print $3}')
            NEW=$(git -C demo2 rev-parse HEAD)
            echo "UPDATE_MSG=Update submodule from $OLD to $NEW" >> $GITHUB_ENV
            git commit -m "Update submodule from $OLD to $NEW"
            echo "Done"
          else
            echo "No changes detected in submodule."
            exit 0
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.UPDATE_MSG }}
          title: "Auto-update submodule"
          body: ${{ env.UPDATE_MSG }}
          base: main
          
