name: Update git submodule and raise PR

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Downstream Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Submodule
        run: |
          ls
          echo "git submodule update"
          git submodule update --remote --merge
          echo "git submodule update...done"
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            branch=$(date +%s)
            git checkout -b update-submodule-$branch
            git branch
            git status
            git add .
            echo "git commit"
            git commit -m "Update submodule to latest commit"
            git log
            echo "git push"
            git push origin update-submodule-$branch
            echo "Done"
          else
            echo "No changes detected in submodule."
            exit 0
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update submodule to latest commit"
          branch: update-submodule
          title: "Auto-update submodule"
          body: "This PR updates the submodule to the latest upstream changes."
          base: main
          labels: |
            submodule-update
